services:

  mbdn-members-db:
    image: postgres
    container_name: mbdn-members-db
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: membersdb
    ports:
      - 5432:5432
    volumes:
      - mbdn-members-db-data:/var/lib/postgresql/data
    networks:
      - mbdn-network

  mbdn-contacts-db:
    image: postgres
    container_name: mbdn-contacts-db
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: contactsdb
    ports:
      - 5434:5432
    volumes:
      - mbdn-contacts-db-data:/var/lib/postgresql/data
    networks:
      - mbdn-network

  mbdn-ibm-mq:
    image: icr.io/ibm-messaging/mq:latest
    container_name: mbdn-ibm-mq
    restart: always
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: MBDN_QM
      MQ_APP_PASSWORD: passw0rd
    ports:
      - 1414:1414
      - 9443:9443
    volumes:
      - mbdn-ibm-mq-data:/mnt/mqm
      - ./docker-resources/mbdn-ibm-mq:/temp
    networks:
      - mbdn-network

volumes:
  mbdn-members-db-data:
    name: mbdn-members-db-data
  mbdn-contacts-db-data:
    name: mbdn-contacts-db-data
  mbdn-ibm-mq-data:
    name: mbdn-ibm-mq-data

networks:
  mbdn-network:
    name: mbdn-network